### PR TITLE
P1/fixes

### PR DESCRIPTION
**Pull request by allan23**
This PR addresses issues #19 , #22 , #23 , and #26 .
* Slugs are now set to use solr-power.
* Options page is organized into tabs.
* Each option tab is moved to a separate view file for better management moving forward.
* Option settings are now saving correctly.

Please let me know if you have any questions.

### CODE REVIEW

**Comment by allan23** [comment]
Also addresses #29 .

**Comment by joshkoenig** [comment]
Hey @allan23 - I am doing the following to attempt to test this PR and am hitting errors:

1. Start fresh WordPress site on Pantheon
2. Install WordPress
3. Add the plugin by pulling the zip file from github (https://github.com/allan23/solr-for-wordpress-on-pantheon/archive/p1/fixes.zip)
4. Clicking activate appears to cause a 500 with nothing going into the error log that I can see.

Is there a piece that I'm missing in terms of getting the naming set?

**Comment by joshkoenig** [comment]
FWIW I get the same result when I copy the plugin over from the `solr-search-experiments` instance on Pantheon as well.

**Comment by joshkoenig** [comment]
Using the installed/working plugin on `solr-search-experiments` to test the new functionality, I can confirm that things appear happier. However, I am seeing the following warning when creating a new post:

```
parameter 2 to be string, array given in /srv/bindings/e3dc75aa5d0445d5991bf0ada7870cd0/code/wp-content/plugins/solr-for-wordpress-on-pantheon/solr-for-wordpress-on-pantheon.php on line 247 Warning: stristr() expects parameter 1 to be string, array given in /srv/bindings/e3dc75aa5d0445d5991bf0ada7870cd0/code/wp-content/plugins/solr-for-wordpress-on-pantheon/solr-for-wordpress-on-pantheon.php on line 250
```

**Comment by joshkoenig** [comment]
One more nit: trying dropping the index and re-loading, the AJAX call is hitting a fatal error:

`Call to undefined function restore_current_blog()`

**Comment by allan23** [comment]
@joshkoenig I'll take a look.

**Comment by joshkoenig** [comment]
Thanks! Let's focus on the install first and I can open separate issues for the bugs once I can reliably replicate on a fresh install.

**Comment by allan23** [comment]
@joshkoenig The last few commits address the errors you have encountered, except that rogue 500 error which I cannot reproduce.

**Comment by joshkoenig** [comment]
I'll try a fresh install shortly!

**Comment by joshkoenig** [comment]
@allan23 I am getting the same 500 error attempting to install on a _fresh_ WordPress site. Are you able to install on a new site (on Pantheon) successfully?

**Comment by joshkoenig** [comment]
Ok looks like this is a pantheon issue where we are swallowing the WP error page, which comes with a 500 status code. That's a regression on our end I believe since we should be able to distinguish that from a platform-related error.

The missing step in my instructions was "enable solr for that pantheon site". I'm unblocked for review.

**Comment by joshkoenig** [comment]
However, queries to the server are now failing with an error in Solarium?

`Parse error: syntax error, unexpected '[' in /srv/bindings/9f15880e1ecc4c298723ab0dfdc8fdfc/code/wp-content/plugins/solr-for-wordpress-on-pantheon/vendor/solarium/solarium/library/Solarium/Core/Client/Adapter/Curl.php on line 156`

Digging into that.

**Comment by joshkoenig** [comment]
Ok, that was because I tried PHP 5.3.

I'll make sure we mark 5.5 or better as a requirement!

**Pull request merged**
